name: Build
on:
  push:
    branches: ['main']
jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: |
        dotnet build -c Release "Pick.Net.Utilities.Tests"
        dotnet build -c Release "Pick.Net.Utilities.Maui.SourceGenerators.Tests"
    - name: Run Tests
      run: dotnet test -c Release --no-build
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Build Pick.Net.Utilities
      uses: ./.github/workflows/pack.yml
      with:
        project-name: Pick.Net.Utilities
    - name: Build Pick.Net.Utilities.Maui
      uses: ./.github/workflows/pack.yml
      with:
        project-name: Pick.Net.Utilities.Maui
