name: Publish
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  test:
    runs-on: ubuntu-latesst
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: dotnet test -c Release "Pick.Net.Utilities.Maui.SourceGenerators.Tests"
  build:
    runs-on: windows-latest
    needs: test
    strategy:
      matrix:
        package: [ 'Pick.Net.Utilities', 'Pick.Net.Utilities.Maui' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # - name: Verify commit exists in origin/main
    #   run: |
    #     git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    #     git branch --remote --contains | grep origin/main
    - name: Get Version
      run: |
        $VERSION = $env:GITHUB_REF -replace 'refs/tags/v', ''
        Write-Output "Version: $version"
        echo "VERSION=$VERSION" >> $env:GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build
      run: dotnet build -c Release "${{ matrix.package }}" /p:Version=${{ env.VERSION }} /p:BuildNumber=${{ github.run_number }}
    - name: Pack
      run: dotnet pack -c Release --no-build -o .build ${{ matrix.package }} /p:Version=${{ env.VERSION }} /p:BuildNumber=${{ github.run_number }}
    - name: Upload
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ matrix.package }}
        path: .build
    - name: Add Nuget Source
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/dan3988/index.json"
    - name: Push
      run: dotnet nuget push  .build/${{ matrix.package }}.${{ env.VERSION }}.nupkg --source "github" --api-key "${{ secrets.GITHUB_TOKEN }}"
