name: Publish
on:
  push:
    branches: [main]
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        package: [ 'Pick.Net.Utilities', 'Pick.Net.Utilities.Maui' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build -c Release "${{ matrix.package }}" /p:Version=${VERSION}
    - name: Pack
      run: dotnet pack -c Release --no-build -o .build ${{ matrix.package }} /p:Version=${VERSION}
    - name: Upload
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ matrix.package }}
        path: .build
    - name: Add Nuget Source
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Pick-Net/index.json"
    - name: Push
      run: dotnet nuget push ${{ matrix.package }}.${VERSION}.nupkg --source "github"" --api-key ${{ secrets.GITHUB_TOKEN }}